development: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
  pool: 5
  username: <%= ENV['POSTGRESQL_USER'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>

test:
  <<: *default

production:
  <<: *default
